<?php

namespace App\Support\Enum;

class ErrorLogEnum
{
  // Auth
  const REGISTER_ACTION_ERROR = 'REGISTER_ACTION_ERROR';

  // Services
  const GET_CITY_SERVICES_LIST = 'GET_CITY_SERVICES_LIST';
  const STORE_SERVICE_STORE_ERROR = 'STORE_SERVICE_STORE_ERROR';
  const UPDATE_SERVICE_STORE_ERROR = 'UPDATE_SERVICE_STORE_ERROR';
  const SERVICE_VISIT_ACTION_ERROR = 'SERVICE_VISIT_ACTION_ERROR';
  const GET_LAST_ADDED_SERVICES_LIST = 'GET_LAST_ADDED_SERVICES_LIST';

  // City, District
  const GET_CITY_LIST_ACTION_ERROR = 'GET_CITY_LIST_ACTION_ERROR';
  const GET_CITY_DISTRICTS_ACTION_ERROR = 'GET_CITY_DISTRICTS_ACTION_ERROR';
  const GET_CITY_DISTRICT_ACTION_ERROR = 'GET_CITY_DISTRICT_ACTION_ERROR';

  // Categories
  const GET_CATEGORY_LIST_ACTION_ERROR = 'GET_CATEGORY_LIST_ACTION_ERROR';

  // Business
  const STORE_BUSINESS_ACTION_ERROR = 'STORE_BUSINESS_ACTION_ERROR';
  const GET_BUSINESS_ACTION_ERROR = 'GET_BUSINESS_ACTION_ERROR';
  const GET_BUSINESSES_ACTION_ERROR = 'GET_BUSINESSES_ACTION_ERROR';

  // Users
  const GET_USER_LIST_ACTION_ERROR = 'GET_USER_LIST_ACTION_ERROR';
  const UPDATE_USER_ACTION_ERROR = 'UPDATE_USER_ACTION_ERROR';
  const GET_USER_DETAIL_ACTION_ERROR = 'GET_USER_DETAIL_ACTION_ERROR';

  // TELEGRAM
  const SEND_TELEGRAM_MESSAGE_SERVICE_ERROR = 'SEND_TELEGRAM_MESSAGE_SERVICE_ERROR';

  public static function all()
  {
    return [
      // Auth
      self::REGISTER_ACTION_ERROR,
      self::GET_BUSINESS_ACTION_ERROR,
      self::GET_BUSINESSES_ACTION_ERROR,

      // service
      self::STORE_SERVICE_STORE_ERROR,
      self::UPDATE_SERVICE_STORE_ERROR,
      self::GET_CITY_SERVICES_LIST,
      self::GET_LAST_ADDED_SERVICES_LIST,

      // City, Districts
      self::GET_CITY_LIST_ACTION_ERROR,
      self::GET_CITY_DISTRICT_ACTION_ERROR,
      self::GET_CITY_DISTRICTS_ACTION_ERROR,

      // Categories
      self::GET_CATEGORY_LIST_ACTION_ERROR,

      // Business
      self::STORE_BUSINESS_ACTION_ERROR,
    ];
  }

}